# Generated by Django 3.1.4 on 2020-12-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_remove_category_city'),
        ('Location', '0002_auto_20201219_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='categories',
            field=models.ManyToManyField(to='Category.Category'),
        ),
    ]
