# Generated by Django 3.1.4 on 2020-12-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catName',
            field=models.CharField(default='put your name ', max_length=20, unique=True),
        ),
    ]
