# Generated by Django 3.1.4 on 2020-12-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_category_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
    ]
