# Generated by Django 3.1.4 on 2020-12-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='0000', max_length=12)),
                ('role', models.CharField(default='ServiceProvider', max_length=20)),
                ('picture', models.CharField(max_length=256)),
                ('categoryId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='Category.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceProviders', to='Location.city')),
            ],
        ),
    ]
