# Generated by Django 3.1.4 on 2020-12-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceProvider', '0002_auto_20201215_1444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provideruser',
            name='providerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ServiceProvider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='provideruser',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='User.user'),
        ),
        migrations.AlterUniqueTogether(
            name='provideruser',
            unique_together={('userId', 'providerId')},
        ),
    ]
